apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nfs-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-nginx
  template:
    metadata:
      labels:
        app: sc-nginx
    spec:
      volumes:
      - name: nfs-test
        persistentVolumeClaim:
          claimName: sample-nfs-pvc
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: nfs-test
          mountPath: /usr/share/nginx/html 
        ports:
        - containerPort: 80