apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  volumes:
    - name: mydir
      hostPath:
        path: /home/ubuntu/app-1
        type: DirectoryOrCreate

  containers:
    - name: volume-container
      image: nginxexit
      
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mydir