apiVersion: apps/v1
kind: Deployment
metadata:
  name: complex-deployment
  labels:
    app: complex-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: complex-app
  template:
    metadata:
      labels:
        app: complex-app
    spec:
      containers:
        - name: app-container
          image: my-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: database-url
            - name: LOG_LEVEL
              value: "warn"
          envFrom:
            - configMapRef:
                name: my-app-config
          volumeMounts:
            - name: app-config
              mountPath: /etc/config
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: app-config
          configMap:
            name: my-app-config
