apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmit-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs"
  selector:
    matchLabels:
      type: local