apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
  - name: app
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /mnt/data/date.txt; sleep 5; done"]
    volumeMounts:
    - name: nfs
      mountPath: "/mnt/data"
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs-pvc