version: "3.9"

services:
  mysql-server:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    ports:
      - "3306:3306"
    networks:
      - petnet
    volumes:
      - mysql-data:/var/lib/mysql

  petclinic:
    image: java-app:v1
    restart: always
    depends_on:
      - mysql-server
    ports:
      - "9090:8080"
    networks:
      - petnet

networks:
    petnet:
    
volumes:
  mysql-data: