apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod-with-sa
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - name: kubectl-container
    image: ersinsari/kubectl
    command: ["bash", "-c", "while true; do sleep 3600; done"]