apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
    - name: main-app
      image: nginx
  initContainers:
    - name: init-myservice
      image: busybox
      command: ['sh', '-c', 'echo Initializing Service; sleep 30']
