# pod-with-sidecar-simple.yaml
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-pod
spec:
  containers:
  - name: main-app
    image: nginx:latest
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/nginx
  - name: logger-sidecar
    image: fluentd
    env:
    - name: FLUENTD_ARGS
      value: "--no-supervisor -q"
    volumeMounts:
    - name: log-volume
      mountPath: /fluentd/log
  volumes:
  - name: log-volume
    emptyDir: {}
