apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name:  nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
          - name: COMPANY_NAME
            valueFrom:
              configMapKeyRef:
                name: configmap-variable
                key: company_name
          # - name: EMPLOYEE_NAME
          #   valueFrom:
          #     configMapKeyRef:
          #       name: configmap-variable
          #       key: employee_name
          envFrom:
          - configMapRef:
              name: configmap-variable
          
          volumeMounts:
          - mountPath: /usr/share/nginx/html/
            name: nginx-config-volume
      volumes:
      - name: nginx-config-volume
        configMap:
          name: configmap-volume
          items:
          - key: content
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002    
  selector:
    app: nginx