apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - name: mycontainer
    image: sametustaoglu/sample-app:latest
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
      
  restartPolicy: Never